### ISSUE TITLE
PathWatcher registration is very slow for large directory structure

### ISSUE THREAD

**Issue by crt-31** [swoval/swoval#161]
Using Metals with a large directory structure is causing the initialization of file-watchers to take a very very long time (14 minutes on my directory structure). See https://github.com/scalameta/metals/issues/5160. In this stage it Metals is registering lots of folders using swoval's PathWather.register().  Note I am using Windows 10 and Metals with VSCode.

I think it is related to the fix for #153 / #152, because if I use Metals with swoval 2.1.7, the initialization of file-watchers takes about 1.5 minutes, but with swoval 2.1.8 or later it takes 14 minutes. 

My hunch is that there is some unnecessary or redundant traversing of the file system happening, as I can see a lot happening using procmon. 

Anyway, I hope this can be addressed as we cannot use Metals for our large repository due to the long initialization time. Thanks.

**Comment by eatkins** [comment]
I think your assessment looks correct. I released v2.1.10 (see #162) that restores a similar condition that existed in 2.1.7 that prevents full directory updates in most cases.

As a side note, I'm sure you have a good reason for using Windows, but the file system performance is terrible. Some operations are quite literally 1000x slower than on Linux. Given how large it sounds like your repository is, you could potentially have a much better experience if you could use Linux (or mac) for development.

I'm closing this issue because I suspect 2.1.10 should restore the 2.1.7 performance, but let me know if that is not the case once metals updates.

**Comment by tgodzik** [comment]
Potentially, one could use linux subsystem for windows with WSL, it should work better than plain Windows.

**Comment by crt-31** [comment]
Thanks for the quick response.
But I am still having the issue with the latest 2.1.10.

**Comment by eatkins** [comment]
Sorry to hear that. I will reopen the issue, but I don't have much bandwidth to work on this further. One thing I might suggest if possible would be to build your own metals and switch swoval to 2.1.7 and see if the problem persists. If downgrading fixes it, I can make another attempt at trying to rework the logic that fixes https://github.com/scalameta/metals/issues/3379. Given the inherently poor performance of the Windows file system and the fact that Windows represents a relatively small share of scala users (I'm guessing fewer than 20%), I have to prioritize correctness over Windows performance.

I seem to recall now that I think about it that there was a big pull request that refactored how metals used the library https://github.com/scalameta/metals/pull/3758/files. Looking at that PR, it seems possible that if the directories were sorted before registration that it might make a difference: https://github.com/scalameta/metals/blob/6bacf42d0166528688dfc6ca02302f139414953c/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L180-L183, so that is another thing to potentially try if you can build your own metals.

**Comment by crt-31** [comment]
Downgrading current Metals to use swoval 2.1.7 does seem to fix the issue. 1.5 min vs 14 min. 

I'll try the sorting, just not sure which way to sort... I'll try a couple ways.

(also, not sure Windows is to blame just yet, it might just be my very large directory structure... there's like 8000 folders).

**Comment by eatkins** [comment]
Ok, that's helpful information. I did take one more attempt at restoring the 2.1.7 behavior in #164. Could you try building swoval off of the latest develop branch? You should just be able to git clone this repository and run `sbt publishLocal` then update metals to use 2.2.0-SNAPSHOT. I would like to know if the change has the intended effect rather than keep publishing new versions to maven.

> (also, not sure Windows is to blame just yet, it might just be my very large directory structure... there's like 8000 folders).

That you have 8000 folders is certainly part of the reason that the performance is so bad, but it would not be nearly as bad on other platforms. Windows io performance is known to be terrible in part because there are all kinds of anti-virus hooks that are built into the file system.

**Comment by crt-31** [comment]
Issue is still present using the latest changes. Still 11 min.

Let me know and I can keep trying out any changes you need me to (I could probably even try out changes you might make in a dev branch).

**Comment by eatkins** [comment]
I made another update to the main branch. If this update doesn't work, it's going to be hard to proceed. I can't revert the change made in 2.1.8 because it fixed a correctness problem that likely affected more metals users than this performance issues. The best way to fix this would probably be to write a new filewatcher specifically for windows that utilizes the windows api for recursive directory monitoring. I had to do this for mac because the built in jvm apis for file watching in nio didn't even work for mac at the time this library was written. There is no way that I would do this work for free though given that I don't even use scala anymore, let alone Windows. So hopefully this change might work, but otherwise I suspect the options will be:
1) maintain a personal fork of metals that uses swoval 2.1.7
2) switch to wsl or another OS entirely that doesn't have the poor file system performance of windows
3) sponsor the development of my writing a native windows path watcher -- this is probably unrealistic given that my price would be significant but I am throwing it out there in case enough people are impacted and willing to pay for a fix

**Comment by crt-31** [comment]
OK, after some investigation into the code, it looks like the issue is in the Window's NativeDirectoryLister.  When I changed it to use the NioDirectoryLister (using the system parameter) it was amazingly faster.

Windows NativeDirectoryLister: 14 min
NioDirectoryLister (on WIndows): 13 sec

_Why? I don't know, maybe the JNI calls are super slow or something._

So, if NioDirectoryLister is orders of magnitude faster, I'm thinking swoval should set the default to use NioDirecotryLister on Windows.

**Comment by eatkins** [comment]
Ok, that is surprising to me. I definitely would have benchmarked it on smaller repositories and wouldn't have included it if there hadn't been a speedup. Given that the worst case is that horrific though, I agree that making NioDirectoryLister the default for windows is a good choice. Do you want to submit a PR that changes it?

**Comment by eatkins** [comment]
Also it's somewhat weird that the behavior changed in response to java code changes, but I suppose maybe there is something about file access patterns that changed and degraded the behavior further (though I notice that with NIO it is still more than 5x faster than the previous behavior your reported). There is JNI overhead, but on mac and linux, it's minimal compared to the extra time spent in syscalls that the native lister avoids (the nio apis make an unnecessary stat call on each file). Windows is admittedly less tested, but I am still a bit puzzled since semantically the jni code for listing directories is basically the same for all 3 platforms (it just uses a different syscall on windows).

**Comment by crt-31** [comment]
Yeah, I can do PR, but it will be like 3 weeks since I'm leaving on vacation soon.

Some additional context is that my directory structure has lots of (~400) directory trees that are very deep. Each one can be like 20 dirs deep, and all files are in the deepest directories.
For instance:
A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S<all the files>
A/BB/CC/DD/EE/FF/GG/HH/II/JJ/KK/LL/MM/NN/OO/PP/QQ/RR/SS/<all the files>

**Comment by eatkins** [comment]
Ok. I'll see if I get around to it before then, but feel free to open when you get back if I haven't done it already.

**Comment by eatkins** [comment]
BTW, thanks for the debugging. It would have been almost impossible for me to reproduce this but I am glad that we seem to have a fix.

**Comment by eatkins** [comment]
I released v2.1.11 to MavenCentral. Can you confirm that it fixes the issue?

**Comment by crt-31** [comment]
Just tried it. It seems to work. (My patched Metals now sets  up file watchers in  10 sec)!

**Comment by eatkins** [comment]
Great. I will close this when https://github.com/scalameta/metals/pull/5659 is merged. Thanks for your help tracking this down.
